name: CI
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node-version }}

    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Tests
        run: pnpm run test

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
