name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number to use for the release
        required: true

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: github.ref != 'refs/heads/main'
          prerelease: github.ref != 'refs/heads/main'

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  package:
    name: "${{ matrix.os}}: Create and upload cli executable"
    needs: create_release

    strategy:
      matrix:
        node-version: ["14"]
        os: ["Linux", "MacOS", "Windows"]
        include:
          - node-version: 14
            os: Linux
            platform: ubuntu-latest
            target: node14-linux-x64
            artifact-name: linux.x64
            binary-name: ynab-sync
            asset-name: ynab-sync-linux-x64
          - node-version: 14
            os: MacOS
            platform: macos-latest
            target: node14-macos-x64
            artifact-name: macos.x64
            binary-name: ynab-sync
            asset-name: ynab-sync-macos-x64
          - node-version: 14
            os: Windows
            platform: windows-latest
            target: node14-win-x64
            artifact-name: win.x64
            binary-name: ynab-sync.exe
            asset-name: ynab-sync-win-x64.exe

    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6

      - name: Install Dependencies
        run: pnpm install

      - name: Create CLI Package
        run: "pnpm run ci:pkg -- -- --target ${{ matrix.target }} --output ./bin/cli/${{ matrix.binary-name }}"

      - name: Publish CLI Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: packages/cli/bin/cli/${{ matrix.binary-name }}

      - name: Upload CLI
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: packages/cli/bin/cli/${{ matrix.binary-name }}
          asset_name: ${{ matrix.asset-name }}
          asset_content_type: application/octet-stream

  nuget:
    name: Create NuGet Package
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create content directory
        run: mkdir ./content

      - uses: actions/download-artifact@v2
        with:
          path: ./content

      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/geofflamrock/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore
        run: dotnet restore ./nuget

      - name: Pack
        run: dotnet pack ./nuget -p:PackageVersion=${{ github.event.inputs.version }} --no-build --no-restore --output ./dist --configuration Release

      - name: Push
        run: dotnet nuget push ./dist/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
