name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number to use for the release
        required: true

jobs:
  build:
    name: "${{ matrix.os}}: Create cli executable"

    strategy:
      matrix:
        node-version: ["14"]
        os: ["Linux", "MacOS", "Windows"]
        include:
          - node-version: 14
            os: Linux
            platform: ubuntu-latest
            target: node14-linux-x64
            cli-exe: ynab-sync-cli-linux
          - node-version: 14
            os: MacOS
            platform: macos-latest
            target: node14-macos-x64
            cli-exe: ynab-sync-cli-macos
          - node-version: 14
            os: Windows
            platform: windows-latest
            target: node14-win-x64
            cli-exe: ynab-sync-cli-win.exe

    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6

      - name: Install Dependencies
        run: pnpm install

      - name: Create CLI Package
        run: "pnpm run pkg -- -- --target ${{ matrix.target }} --output ./bin/cli/${{ matrix.cli-exe }}"

      - name: Publish CLI Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.cli-artifact }}
          path: packages/cli/bin/cli/${{ matrix.cli-exe }}

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          commit: main
          tag: ${{ github.event.inputs.version }}
          artifacts: "**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
