name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number to use for the release
        required: true

jobs:
  build:
    strategy:
      matrix:
        node-version: ["14"]
        platform:
          - ubuntu:
              runner: ubuntu-latest
              target: node14-linux-x64
          - macos:
              runner: macos-latest
              target: node14-macos-x64
          - windows:
              runner: windows-latest
              target: node14-win-x64

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6

      - name: Install Dependencies
        run: pnpm install

      - name: Create Packages
        run: pnpm pkg -- -- --target ${{ matrix.platform.runner }}

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          commit: main
          tag: ${{ github.event.inputs.version }}
          artifacts: packages/cli/bin/cli/*
          token: ${{ secrets.GITHUB_TOKEN }}
